version: '5'

services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: 'orderService-postgres'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=${DB_NAME}'
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: orderService-inno
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/changelog/db.changelog-master.xml
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge